sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mkargul/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkargul/react-test npm test

after_success:
  - docker build -t mkargul/multi-client ./client
  - docker build -t mkargul/multi-nginx ./nginx
  - docker build -t mkargul/multi-server ./server
  - docker build -t mkargul/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docket hub
  - docker push mkargul/multi-client
  - docker push mkargul/multi-nginx
  - docker push mkargul/multi-server
  - docker push mkargul/multi-worker
